---
- name: Add Java PPA repo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: Add OpenDistro apt key
  apt_key:
    url: https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
    state: present

- name: Add specified repository into sources list using specified filename
  apt_repository:
    repo: deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main
    state: present
    filename: opendistro

- name: Add OpenDistro apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add specified repository into sources list using specified filename
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main
    state: present
    filename: opendistro

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - openjdk-11-jdk
      - unzip
      - "elasticsearch-oss={{ opendistro_elasticsearch_version }}"
      - "logstash-oss=1:{{ opendistro_elasticsearch_version }}-1"
      - "opendistroforelasticsearch={{ opendistro_opendistro_version }}"
      - "opendistroforelasticsearch-kibana={{ opendistro_opendistro_version }}"
      - "filebeat={{ opendistro_elasticsearch_version }}"
    state: present
    update_cache: true

- name: Enable elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

# A little of black magic to make init-script work from Ansible
- name: Slurp kibana init script
  slurp:
    src: /etc/init.d/kibana
  register: slurpfile

- name: dest
  command:
    cmd: sed -i '1 i#!/bin/sh' /etc/init.d/kibana
    warn: false
  when: (slurpfile['content'] | b64decode).split('\n')[0] != '#!/bin/sh'

- name: Configure kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Enable kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: Configure logstash
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Enable logstash
  service:
    name: logstash
    state: started
    enabled: true

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  notify: restart filebeat

- name: Enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true
