---
- name: restart kibana
  service:
    name: kibana
    state: restarted

- name: restart logstash
  service:
    name: logstash
    state: restarted

- name: restart filebeat
  service:
    name: filebeat
    state: restarted
