---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: .imported_roles
    force: false

driver:
  name: docker

lint: |
  set -e
  yamllint .
  flake8
  ansible-lint

platforms:
  - name: elastic
    image: ubuntu:18.04
    published_ports:
      - 127.0.0.1:8080:80/tcp

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
  lint:
    name: ansible-lint
scenario:
  name: default
